package model.workout.repository;

import config.DatabaseConnection;
import model.workout.domain.PlanContext;
import model.workout.enums.MuscleGroup;

import java.sql.*;
public class PlanContextRepository {

    public String saveContext(PlanContext context) {
        Connection conn = null;
        PreparedStatement ctxStmt = null;
        PreparedStatement wpStmt = null;

        // Context ID is generated by DB
        String insertCtxSql = "INSERT INTO plan_contexts (profile_id, training_split, training_days, difficulty) VALUES (?, ?, ?, ?)";
        String insertWpSql = "INSERT INTO context_weak_points (context_id, muscle_group) VALUES (?, ?)";

        try {
            conn = DatabaseConnection.getInstance().getConnection();
            conn.setAutoCommit(false);

            // 0. Clean up existing contexts (Overwrite Policy)
            // Must delete weak points first (FK constraint)
            String deleteWpSql = "DELETE FROM context_weak_points WHERE context_id IN (SELECT context_id FROM plan_contexts WHERE profile_id = ?)";
            String deleteCtxSql = "DELETE FROM plan_contexts WHERE profile_id = ?";

            try (PreparedStatement delWpStmt = conn.prepareStatement(deleteWpSql);
                    PreparedStatement delCtxStmt = conn.prepareStatement(deleteCtxSql)) {

                delWpStmt.setString(1, context.getProfile().getProfileId());
                delWpStmt.executeUpdate();

                delCtxStmt.setString(1, context.getProfile().getProfileId());
                delCtxStmt.executeUpdate();
            }

            // 1. Insert Context
            ctxStmt = conn.prepareStatement(insertCtxSql, Statement.RETURN_GENERATED_KEYS);
            ctxStmt.setString(1, context.getProfile().getProfileId());
            ctxStmt.setString(2, context.getSplit().name());
            ctxStmt.setInt(3, context.getTrainingDays());
            ctxStmt.setString(4, "INTERMEDIATE");
            ctxStmt.executeUpdate();

            // Retrieve generated Context ID
            String contextId = null;
            try (ResultSet generatedKeys = ctxStmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    contextId = String.valueOf(generatedKeys.getInt(1));
                } else {
                    throw new SQLException("Creating plan context failed, no ID obtained.");
                }
            }

            // 2. Insert Weak Points
            wpStmt = conn.prepareStatement(insertWpSql);
            for (MuscleGroup mg : context.getWeakPoints()) {
                wpStmt.setInt(1, Integer.parseInt(contextId)); // Linked via ID
                wpStmt.setString(2, mg.name());
                wpStmt.executeUpdate();
            }

            // Note: Equipment preferences and Restrictions are not strictly in the base ERD
            // tables provided,
            // so we skip them to avoid SQL errors, or assuming custom tables.
            // If context_restrictions exists, we could save something, but
            // context.getRestrictions() (if any)

            conn.commit();
            return contextId;

        } catch (SQLException e) {
            e.printStackTrace();
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            return null;
        } finally {
            try {
                if (wpStmt != null)
                    wpStmt.close();
                if (ctxStmt != null)
                    ctxStmt.close();
                if (conn != null)
                    conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
