package model.workout.repository;

import config.DatabaseConnection;
import model.workout.domain.WorkoutPlan;
import model.workout.domain.WorkoutDay;
import model.workout.domain.WorkoutExerciseEntry;
import model.user.domain.Profile;

import java.sql.*;

public class WorkoutRepository {

    public String saveWorkoutPlan(WorkoutPlan plan, Profile profile) {
        Connection conn = null;
        PreparedStatement planStmt = null;
        PreparedStatement dayStmt = null;
        PreparedStatement exStmt = null;

        // Plan ID is now generated by DB

        try {
            conn = DatabaseConnection.getInstance().getConnection();
            conn.setAutoCommit(false);

            // 0. Clean up existing plans (Overwrite Policy)
            // We must delete children first to avoid FK constraints if CASCADE isn't set
            String deleteExSql = "DELETE FROM workout_exercises WHERE day_id IN (SELECT day_id FROM workout_days WHERE plan_id IN (SELECT plan_id FROM workout_plans WHERE profile_id = ?))";
            String deleteDaysSql = "DELETE FROM workout_days WHERE plan_id IN (SELECT plan_id FROM workout_plans WHERE profile_id = ?)";
            String deletePlanSql = "DELETE FROM workout_plans WHERE profile_id = ?";

            try (PreparedStatement delExStmt = conn.prepareStatement(deleteExSql);
                    PreparedStatement delDayStmt = conn.prepareStatement(deleteDaysSql);
                    PreparedStatement delPlanStmt = conn.prepareStatement(deletePlanSql)) {

                delExStmt.setString(1, profile.getProfileId());
                delExStmt.executeUpdate();

                delDayStmt.setString(1, profile.getProfileId());
                delDayStmt.executeUpdate();

                delPlanStmt.setString(1, profile.getProfileId());
                int deleted = delPlanStmt.executeUpdate();
                if (deleted > 0) {
                    System.out.println("ℹ️  Overwriting existing workout plan for user.");
                }
            }

            // 1. Insert Plan (Let DB generate ID)
            String planSql = "INSERT INTO workout_plans (profile_id, goal, created_at) VALUES (?, ?, ?)";
            // Map Java Enum to DB Check Constraint values
            String dbGoal = profile.getGoal().toString();
            if (profile.getGoal() == model.user.enums.GoalType.GAIN_WEIGHT) {
                dbGoal = "GAIN_MUSCLE";
            } else if (profile.getGoal() == model.user.enums.GoalType.MAINTENANCE) {
                dbGoal = "MAINTAIN";
            } // LOSE_WEIGHT is the same

            planStmt = conn.prepareStatement(planSql, Statement.RETURN_GENERATED_KEYS);
            planStmt.setString(1, profile.getProfileId());
            planStmt.setString(2, dbGoal);
            planStmt.setTimestamp(3, new Timestamp(System.currentTimeMillis()));
            planStmt.executeUpdate();

            // Retrieve generated plan ID
            String planId = null;
            try (ResultSet generatedKeys = planStmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    planId = String.valueOf(generatedKeys.getInt(1));
                } else {
                    throw new SQLException("Creating workout plan failed, no ID obtained.");
                }
            }

            // 2. Insert Days and Exercises
            String daySql = "INSERT INTO workout_days (plan_id, day_index) VALUES (?, ?)"; // DB generates day_id
            String exSql = "INSERT INTO workout_exercises (day_id, exercise_id, sets, min_reps, max_reps, order_index) VALUES (?, ?, ?, ?, ?, ?)"; // Added
                                                                                                                                                   // order_index

            dayStmt = conn.prepareStatement(daySql, Statement.RETURN_GENERATED_KEYS);
            exStmt = conn.prepareStatement(exSql);

            int dayIndex = 1;
            for (WorkoutDay day : plan.getDays()) {
                // Day
                dayStmt.setInt(1, Integer.parseInt(planId)); // plan_id FK
                dayStmt.setInt(2, dayIndex);
                dayStmt.executeUpdate();

                // Get generated day_id
                int dayIdInt;
                try (ResultSet rsDay = dayStmt.getGeneratedKeys()) {
                    if (rsDay.next()) {
                        dayIdInt = rsDay.getInt(1);
                    } else {
                        throw new SQLException("Creating workout day failed, no ID obtained.");
                    }
                }

                // Exercises
                int exerciseIndex = 1; // Track order
                for (WorkoutExerciseEntry ex : day.getExercises()) {
                    // Check if exercise exists in catalog to get ID
                    int exerciseId = -1;
                    String checkExSql = "SELECT exercise_id FROM exercises WHERE name = ?";
                    try (PreparedStatement checkStmt = conn.prepareStatement(checkExSql)) {
                        checkStmt.setString(1, ex.getExerciseName());
                        try (ResultSet rsEx = checkStmt.executeQuery()) {
                            if (rsEx.next()) {
                                exerciseId = rsEx.getInt("exercise_id");
                            }
                        }
                    }

                    // If not found, insert it (Auto-cataloging)
                    if (exerciseId == -1) {
                        String insertExCatalogSql = "INSERT INTO exercises (name, target_muscle) VALUES (?, ?)";
                        try (PreparedStatement insertExStmt = conn.prepareStatement(insertExCatalogSql,
                                Statement.RETURN_GENERATED_KEYS)) {
                            // Map granular MuscleGroup to DB broad categories
                            String targetMuscle = "FULL_BODY";
                            switch (ex.getMuscleGroup()) {
                                case CHEST:
                                    targetMuscle = "CHEST";
                                    break;
                                case BACK:
                                case LATS:
                                case TRAPS:
                                    targetMuscle = "BACK";
                                    break;
                                case SHOULDERS:
                                    targetMuscle = "SHOULDERS";
                                    break;
                                case BICEPS:
                                case TRICEPS:
                                case FOREARMS:
                                    targetMuscle = "ARMS";
                                    break;
                                case QUADRICEPS:
                                case HAMSTRINGS:
                                case GLUTES:
                                case CALVES:
                                    targetMuscle = "LEGS";
                                    break;
                                case ABS:
                                    targetMuscle = "CORE";
                                    break;
                            }
                            insertExStmt.setString(1, ex.getExerciseName());
                            insertExStmt.setString(2, targetMuscle);
                            insertExStmt.executeUpdate();
                            try (ResultSet genExKeys = insertExStmt.getGeneratedKeys()) {
                                if (genExKeys.next()) {
                                    exerciseId = genExKeys.getInt(1);
                                } else {
                                    throw new SQLException(
                                            "Failed to create catalog entry for exercise: " + ex.getExerciseName());
                                }
                            }
                        }
                    }

                    exStmt.setInt(1, dayIdInt); // FK to day
                    exStmt.setInt(2, exerciseId); // FK to exercise
                    exStmt.setInt(3, ex.getSets());
                    exStmt.setInt(4, ex.getRepsRange().getMinReps());
                    exStmt.setInt(5, ex.getRepsRange().getMaxReps());
                    exStmt.setInt(6, exerciseIndex++); // Set order and increment
                    exStmt.executeUpdate();
                }
                dayIndex++;
            }

            conn.commit();
            return planId;

        } catch (SQLException e) {
            e.printStackTrace();
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            return null;
        } finally {
            try {
                if (exStmt != null)
                    exStmt.close();
                if (dayStmt != null)
                    dayStmt.close();
                if (planStmt != null)
                    planStmt.close();
                if (conn != null)
                    conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public WorkoutPlan getWorkoutPlan(Profile profile) {
        Connection conn = null;
        PreparedStatement planStmt = null;
        PreparedStatement ctxStmt = null;
        PreparedStatement dayStmt = null;
        PreparedStatement exStmt = null;
        ResultSet rsPlan = null;
        ResultSet rsCtx = null;
        ResultSet rsDay = null;
        ResultSet rsEx = null;

        try {
            conn = DatabaseConnection.getInstance().getConnection();

            // 1. Get Plan
            String planSql = "SELECT plan_id, created_at FROM workout_plans WHERE profile_id = ?";
            planStmt = conn.prepareStatement(planSql);
            planStmt.setString(1, profile.getProfileId());
            rsPlan = planStmt.executeQuery();

            if (!rsPlan.next()) {
                return null; // No plan found
            }
            int planId = rsPlan.getInt("plan_id");

            // 2. Get Split from Context (needed for WorkoutDay constructor)
            model.workout.enums.TrainingSplit split = model.workout.enums.TrainingSplit.FULL_BODY; // Default
            String ctxSql = "SELECT training_split FROM plan_contexts WHERE profile_id = ?";
            ctxStmt = conn.prepareStatement(ctxSql);
            ctxStmt.setString(1, profile.getProfileId());
            rsCtx = ctxStmt.executeQuery();
            if (rsCtx.next()) {
                try {
                    split = model.workout.enums.TrainingSplit.valueOf(rsCtx.getString("training_split"));
                } catch (Exception e) {
                }
            }

            // 3. Get Days
            java.util.List<WorkoutDay> days = new java.util.ArrayList<>();
            String daySql = "SELECT day_id, day_index FROM workout_days WHERE plan_id = ? ORDER BY day_index ASC";
            dayStmt = conn.prepareStatement(daySql);
            dayStmt.setInt(1, planId);
            rsDay = dayStmt.executeQuery();

            while (rsDay.next()) {
                int dayId = rsDay.getInt("day_id");
                int dayIndex = rsDay.getInt("day_index");

                // 4. Get Exercises for this Day
                java.util.List<WorkoutExerciseEntry> exercises = new java.util.ArrayList<>();
                String exSql = "SELECT we.sets, we.min_reps, we.max_reps, e.name, e.target_muscle " +
                        "FROM workout_exercises we " +
                        "JOIN exercises e ON we.exercise_id = e.exercise_id " +
                        "WHERE we.day_id = ? " +
                        "ORDER BY we.order_index ASC";
                exStmt = conn.prepareStatement(exSql);
                exStmt.setInt(1, dayId);
                rsEx = exStmt.executeQuery();

                while (rsEx.next()) {
                    String exName = rsEx.getString("name");
                    String muscleStr = rsEx.getString("target_muscle");
                    int sets = rsEx.getInt("sets");
                    int minReps = rsEx.getInt("min_reps");
                    int maxReps = rsEx.getInt("max_reps");

                    model.workout.enums.MuscleGroup mg = model.workout.enums.MuscleGroup.CHEST; // Default
                    try {
                        if (muscleStr.equals("LEGS"))
                            mg = model.workout.enums.MuscleGroup.QUADRICEPS;
                        else if (muscleStr.equals("ARMS"))
                            mg = model.workout.enums.MuscleGroup.BICEPS;
                        else if (muscleStr.equals("CORE"))
                            mg = model.workout.enums.MuscleGroup.ABS;
                        else
                            mg = model.workout.enums.MuscleGroup.valueOf(muscleStr);
                    } catch (Exception e) {
                    }

                    WorkoutExerciseEntry entry = new WorkoutExerciseEntry(
                            exName,
                            mg,
                            sets,
                            new model.workout.domain.RepsRange(minReps, maxReps));
                    exercises.add(entry);
                }
                rsEx.close();
                exStmt.close();

                // Construct Immutable WorkoutDay
                WorkoutDay workoutDay = new WorkoutDay(dayIndex, split, exercises);
                days.add(workoutDay);
            }

            // Construct Immutable WorkoutPlan
            return new WorkoutPlan(days, profile.getProfileId(), profile.getGoal());

        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        } finally {
            try {
                if (rsPlan != null)
                    rsPlan.close();
                if (rsCtx != null)
                    rsCtx.close();
                if (rsDay != null)
                    rsDay.close();
                if (rsEx != null)
                    rsEx.close();
                if (planStmt != null)
                    planStmt.close();
                if (ctxStmt != null)
                    ctxStmt.close();
                if (dayStmt != null)
                    dayStmt.close();
                if (exStmt != null)
                    exStmt.close();
                if (conn != null)
                    conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
